id: IF34782F7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T23:28:20+00:00'
last_modified: '2022-06-07T12:00:09.482054+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG15578
  title: བརྒྱད་སྟོང་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    023A:
      image_group_id: I1KG21261
      title: Volume 1 of brgyad stong pa/
      total_pages: 1156
      order: 1
      base_file: 023A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
